# Generated by Django 6.1 on 2026-09-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_usuario', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=16)),
                ('nombre', models.CharField(max_length=60)),
                ('estatus', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
