# Generated by Django 6.1.1 on 2026-09-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permanencia',
            fields=[
                ('id_permanencia', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre_perma', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('siglas', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'cat_permanencias',
                'managed': False,
            },
        ),
    ]
