# Generated by Django 6.1.1 on 2026-09-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id_linea', models.CharField(max_length=2)),
                ('id_estacion', models.CharField(max_length=2)),
                ('nombre_estacion', models.CharField(max_length=25)),
                ('pk', models.CompositePrimaryKey('id_linea', 'id_estacion', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cat_estaciones',
                'managed': False,
            },
        ),
    ]
