# Generated by Django 6.1.1 on 2026-09-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_estacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descanso',
            fields=[
                ('id_descansos', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('iniciales', models.CharField(max_length=2)),
                ('descanso1', models.CharField(max_length=10)),
                ('descanso2', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'cat_descansos',
                'managed': False,
            },
        ),
    ]
