# Generated by Django 6.1.1 on 2026-09-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_descanso'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTaquilla',
            fields=[
                ('id_expediente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField()),
                ('prejubilacion', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'cat_personal_taquilla',
                'managed': False,
            },
        ),
    ]
